import React, { useMemo } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Alert, Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { StackNavigationProp } from '@react-navigation/stack';
import { RootStackParamList, UserData } from '../../App';
import { useTheme } from '../constants/colors';
import { MaterialIcons } from '@expo/vector-icons';

type Props = {
  navigation: StackNavigationProp<RootStackParamList, 'Profile'>;
  user: UserData;
  onLogout: () => void;
};

export default function ProfileScreen({ navigation, user, onLogout }: Props) {
  const { colors, isDark, toggleTheme } = useTheme();
  const styles = useMemo(() => getStyles(colors), [colors]);

  const menuItems = [
    { icon: isDark ? 'light-mode' : 'dark-mode', label: isDark ? 'Light Mode' : 'Dark Mode', desc: 'Toggle app theme', action: toggleTheme },
    { icon: 'calendar-month', label: 'My Bookings', desc: 'View your booking history', action: () => navigation.navigate('MyBookings') },
    ...(user.isProvider ? [] : [{ icon: 'handyman', label: 'Become a Provider', desc: 'Register as a service professional', action: () => navigation.navigate('ProviderRegister') }]),
    { icon: 'help-outline', label: 'Help & Support', desc: 'FAQs and contact support', action: () => Alert.alert('Help & Support - FAQs', '1. How do I book a service?\nSearch for your required service using the AI agent or categories, select a provider, and tap "Book Now".\n\n2. How are prices calculated?\nPrices are dynamically generated by our AI based on the provider\'s base rate, urgency, and job complexity.\n\n3. What if a provider doesn\'t show up?\nYou can file a dispute from the "My Bookings" screen and our AI Dispute Agent will resolve it.') },
    { icon: 'info-outline', label: 'About Khidmat', desc: 'Version 1.0 — Hackathon Build', action: () => Alert.alert('About Khidmat', "Khidmat is Pakistan's first AI-powered informal economy platform, designed to connect skilled workers with customers.\n\nVersion: 1.0.0\nPowered by: Gemini 2.0 Flash\nBuilt with ❤️ by Team Khidmat for the Google Antigravity Hackathon.") },
  ];

  const handleLogout = () => {
    if (Platform.OS === 'web') {
      // On web, window.confirm works better than Alert.alert
      const confirmed = window.confirm('Are you sure you want to logout?');
      if (confirmed) onLogout();
    } else {
      Alert.alert('Logout', 'Are you sure you want to logout?', [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Logout', style: 'destructive', onPress: onLogout },
      ]);
    }
  };

  return (
    <View style={styles.container}>
      <SafeAreaView style={{ flex: 1 }} edges={['top']}>
        <View style={styles.header}>
          <View style={styles.headerLeft}>
            <TouchableOpacity onPress={() => navigation.goBack()}>
              <MaterialIcons name="arrow-back" size={24} color={colors.primary} />
            </TouchableOpacity>
            <Text style={styles.headerTitle}>Profiles</Text>
          </View>
        </View>

        <ScrollView style={styles.main} contentContainerStyle={styles.mainContent} showsVerticalScrollIndicator={false}>
          {/* User Profile Card */}
          <View style={styles.profileCard}>
            <Text style={{ fontSize: 12, fontWeight: '700', color: colors.outline, alignSelf: 'flex-start', marginLeft: 16, marginTop: -16, marginBottom: 8 }}>USER PROFILE</Text>
            <View style={styles.avatarLarge}>
              <Text style={styles.avatarText}>{user.name.charAt(0).toUpperCase()}</Text>
            </View>
            <Text style={styles.profileName}>{user.name}</Text>
            <Text style={styles.profilePhone}>{user.phone || user.email}</Text>
            <View style={styles.cityBadge}>
              <MaterialIcons name="person" size={14} color={colors.primary} />
              <Text style={styles.cityText}>Customer Mode</Text>
            </View>
          </View>

          {/* Provider Profile Card (if registered) */}
          {user.isProvider && (
            <TouchableOpacity 
              style={[styles.profileCard, { marginTop: 12, backgroundColor: colors.primaryContainer, borderColor: colors.primary }]}
              onPress={() => navigation.navigate('ProviderDashboard')}
              activeOpacity={0.9}
            >
              <Text style={{ fontSize: 12, fontWeight: '700', color: colors.primary, alignSelf: 'flex-start', marginLeft: 16, marginTop: -16, marginBottom: 8 }}>PROVIDER PROFILE</Text>
              <View style={[styles.avatarLarge, { backgroundColor: colors.primary, borderColor: colors.surface }]}>
                <MaterialIcons name="handyman" size={40} color={colors.onPrimary} />
              </View>
              <Text style={[styles.profileName, { color: colors.onPrimaryContainer }]}>{user.name}</Text>
              <Text style={[styles.profilePhone, { color: colors.onPrimaryContainer }]}>Active Professional</Text>
              <View style={[styles.cityBadge, { backgroundColor: colors.surface }]}>
                <MaterialIcons name="dashboard" size={14} color={colors.primary} />
                <Text style={styles.cityText}>Open Provider Dashboard →</Text>
              </View>
            </TouchableOpacity>
          )}

          {/* Menu Items */}
          <View style={styles.menuSection}>
            {menuItems.map((item, idx) => (
              <TouchableOpacity key={idx} style={styles.menuItem} onPress={item.action} activeOpacity={0.7}>
                <View style={styles.menuIconBox}>
                  <MaterialIcons name={item.icon as any} size={22} color={colors.primary} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.menuLabel}>{item.label}</Text>
                  <Text style={styles.menuDesc}>{item.desc}</Text>
                </View>
                <MaterialIcons name="chevron-right" size={20} color={colors.outline} />
              </TouchableOpacity>
            ))}
          </View>

          {/* Logout */}
          <TouchableOpacity style={styles.logoutBtn} onPress={handleLogout} activeOpacity={0.85}>
            <MaterialIcons name="logout" size={20} color="#d32f2f" />
            <Text style={styles.logoutText}>Logout</Text>
          </TouchableOpacity>

          {/* App Info */}
          <View style={styles.appInfo}>
            <Text style={styles.appInfoTitle}>Khidmat AI</Text>
            <Text style={styles.appInfoSub}>Pakistan's AI-Powered Service Platform</Text>
            <Text style={styles.appInfoVersion}>v1.0.0 • Built with Gemini AI</Text>
          </View>

          <View style={{ height: 80 }} />
        </ScrollView>

        {/* Bottom Nav */}
        <View style={styles.bottomNav}>
          <TouchableOpacity style={styles.navItem} onPress={() => navigation.navigate('Home')}>
            <MaterialIcons name="home" size={24} color={colors.onSurfaceVariant} />
            <Text style={styles.navLabel}>Home</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.navItem} onPress={() => navigation.navigate('MyBookings')}>
            <MaterialIcons name="calendar-month" size={24} color={colors.onSurfaceVariant} />
            <Text style={styles.navLabel}>My Bookings</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.navItemActive}>
            <MaterialIcons name="person" size={24} color={colors.onPrimaryContainer} />
            <Text style={styles.navLabelActive}>Profile</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    </View>
  );
}

const getStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    ...Platform.select({ web: { height: '100vh' as any, overflow: 'hidden' as any }, default: {} }),
  },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', height: 56, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: colors.outlineVariant, backgroundColor: colors.surface },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerTitle: { fontSize: 20, fontWeight: '700', color: colors.primary },
  main: { flex: 1 },
  mainContent: { paddingHorizontal: 16, paddingBottom: 16 },
  profileCard: { alignItems: 'center', paddingVertical: 32, backgroundColor: colors.surfaceContainerLowest, borderRadius: 16, marginTop: 16, borderWidth: 1, borderColor: colors.outlineVariant, elevation: 2 },
  avatarLarge: { width: 88, height: 88, borderRadius: 44, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginBottom: 12, borderWidth: 3, borderColor: colors.primaryContainer },
  avatarText: { fontSize: 36, fontWeight: '700', color: colors.onPrimary },
  profileName: { fontSize: 22, fontWeight: '700', color: colors.onSurface },
  profilePhone: { fontSize: 14, color: colors.onSurfaceVariant, marginTop: 2 },
  cityBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 8, backgroundColor: colors.aiInsight, paddingHorizontal: 12, paddingVertical: 4, borderRadius: 16 },
  cityText: { fontSize: 12, fontWeight: '600', color: colors.primary },
  menuSection: { marginTop: 20, gap: 2 },
  menuItem: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: colors.surfaceContainerLowest, paddingHorizontal: 16, paddingVertical: 14, borderRadius: 12, marginBottom: 8, borderWidth: 1, borderColor: colors.outlineVariant },
  menuIconBox: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.aiInsight, alignItems: 'center', justifyContent: 'center' },
  menuLabel: { fontSize: 15, fontWeight: '600', color: colors.onSurface },
  menuDesc: { fontSize: 12, color: colors.onSurfaceVariant, marginTop: 1 },
  logoutBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 16, paddingVertical: 14, borderRadius: 12, borderWidth: 1.5, borderColor: '#d32f2f' },
  logoutText: { fontSize: 15, fontWeight: '600', color: '#d32f2f' },
  appInfo: { alignItems: 'center', marginTop: 24, paddingVertical: 16 },
  appInfoTitle: { fontSize: 18, fontWeight: '700', color: colors.primary },
  appInfoSub: { fontSize: 12, color: colors.onSurfaceVariant, marginTop: 2 },
  appInfoVersion: { fontSize: 10, color: colors.outline, marginTop: 4 },
  bottomNav: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', height: 64, backgroundColor: colors.surfaceContainer, borderTopWidth: 1, borderTopColor: colors.outlineVariant, borderTopLeftRadius: 12, borderTopRightRadius: 12, elevation: 8 },
  navItem: { alignItems: 'center', paddingHorizontal: 16, paddingVertical: 4 },
  navItemActive: { alignItems: 'center', backgroundColor: colors.primaryContainer, paddingHorizontal: 16, paddingVertical: 4, borderRadius: 12 },
  navLabel: { fontSize: 10, fontWeight: '500', color: colors.onSurfaceVariant, marginTop: 2 },
  navLabelActive: { fontSize: 10, fontWeight: '500', color: colors.onPrimaryContainer, marginTop: 2 },
});
